emersion/go-imap

client/cmd_selected.go

When searching fall back to US-ASCII if BADCHARSET is received.

---

server/conn.go
server/server.go

Only send responses when the client waits for them

---

server/conn.go
server/server.go

server: adds Server.AutoLogout

---

backend/mailbox.go
backend/memory/mailbox.go
backend/memory/message.go
internal/testutil.go
mailbox.go
mailbox_test.go
message.go
message_test.go
read.go
read_test.go
responses/select.go
responses/status.go
server/cmd_auth_test.go
server/cmd_selected_test.go
write.go

Make imap.MailboxStatus and imap.Message extendable

---

mailbox.go
mailbox_test.go
server/cmd_auth.go

Adds MailboxInfo.Match

---

client/client.go
logger.go
server/server.go

* which enables easier override for custom behavior
* fixes #74

Make ErrorLog a small interface

---

client/client.go
message_test.go

- fix one formatting in test error

Remove unreachable code in client read

---

message.go
message_test.go
server/cmd_selected_test.go

Keep requested items in order when responding to FETCH

---

backend/backendutil/backendutil.go
backend/backendutil/backendutil_test.go
backend/backendutil/body.go
backend/backendutil/body_test.go
backend/backendutil/bodystructure.go
backend/backendutil/bodystructure_test.go
backend/backendutil/envelope.go
backend/backendutil/envelope_test.go
client/cmd_noauth.go
client/cmd_noauth_test.go
client/example_test.go
message.go
message_test.go

Also fixes incorrect body disposition in body structure.

Adds backendutil package

---

backend/backendutil/flags_test.go
backend/backendutil/search.go
backend/backendutil/search_test.go
backend/memory/backend.go
backend/memory/mailbox.go
backend/memory/message.go
client/cmd_selected_test.go
message_test.go
search.go
search_test.go
server/cmd_selected.go

Improves imap.SearchCriteria

---

message.go
responses/status.go
seqset.go
server/cmd_selected.go

* don't check err, just return
* don't check bool to bool, check bool directly

all: some simplification

---

read.go
read_test.go

Return after getting error on reading CR. Accordingly, updated fields reading.

read: fix crlf reading

---

client/cmd_any_test.go
client/cmd_selected_test.go

* formatted call but no format directive
* formatted call but no need
* intend to print value, but function was given

client: fix couple of formatting issues in tests

---

.travis.yml

travis: make docker based, instead of vm

---

backend/backendutil/backendutil_test.go
backend/backendutil/body.go
backend/backendutil/body_test.go
backend/backendutil/bodystructure_test.go

This matches the description and example in RFC 3501 Section 6.4.5.

backendutil: read body section parts left-to-right

---

client/example_test.go

I'm new in golang and some days ago I spent some hours trying to figure out how to use [Client.Search](https://godoc.org/github.com/emersion/go-imap/client#Client.Search) and finally I understand it but I also found that I wasn't the only one looking for that, see https://github.com/emersion/go-imap/issues/186#issuecomment-392602873 and https://github.com/emersion/go-imap/issues/172. So I decided to write a basic example of searching for unseen messages.
I try to follow the same style of other examples but please don't hesitate to tell if I need to change something and feel free to accept or reject this PR.

Add an example for Client.Search() usage

---

client/client.go
server/conn.go

Need to always wait for the `cmd.WriteTo` to finish before returning
from from `client.execute()`, otherwise another goroutine could be
started before the current on finished.
This data race causes random `short write` errors.

Fix client data race in `client.execute()` method

---

client/client.go
client/client_test.go
client/cmd_noauth.go
conn.go
conn_test.go
responses/authenticate.go
server/cmd_noauth.go
server/conn.go

Fixes the data races in issue #151 .

Fixes client & server data races.

---

backend/backendutil/envelope.go
backend/backendutil/search.go
client/cmd_selected.go
client/cmd_selected_test.go
imap.go
message.go
read_test.go
status.go

* set types for constants
* use underscore for unused results

all: fix some lint issues

---

client/cmd_selected.go
client/cmd_selected_test.go

 Always close ch chan *imap.Message upon fetch

---

backend/backendutil/search.go
backend/backendutil/search_test.go
backend/memory/message.go

Backward-compatibility-breaking change.
Closes #222.

backendutil: Merge Match* functions

---

write.go

Check literal length

---

client/client.go

Use less restrictve Dialer interface in DialWithDialer

---

backend/backendutil/body.go
backend/backendutil/body_test.go

See https://github.com/emersion/maddy/issues/73.

backendutil: Compare header field names in case-insensitive way

---

read.go
read_test.go
server/cmd_any_test.go
server/cmd_noauth_test.go
server/conn.go
server/server_test.go

Not sure if we want something for the client side.

Server-side (reader) support for non-synchronizing literals

---

server/conn.go

server: Add per-connection panic handler

---

client/client_test.go
client/cmd_noauth.go
client/cmd_noauth_test.go
commands/authenticate.go
server/cmd_any_test.go
server/cmd_noauth_test.go
server/conn.go
server/server_test.go

Client & server support for SASL-IR extension

---

client/client.go
client/cmd_auth_test.go

client: cancel pending literal writes after status response

---

backend/backendutil/body.go

https://stackoverflow.com/a/9842589/1316157

fix detection of multipart in different case

---

backend/backendutil/search.go
backend/backendutil/search_test.go

Fix search larger and smaller edge case

---

client/client.go
client/cmd_auth_test.go
write.go

Improve handling of mismatched literal length

---

message.go
message_test.go

This is a helper to iterate over a body structure tree.
Closes: https://github.com/emersion/go-imap/issues/319

Introduce BodyStructure.Walk

---

message.go

Fixes: https://github.com/emersion/go-imap/issues/331
fix the rfc822XXX untag response data

fix rfc822XXX issue

---

utf7/utf7.go

Same as https://github.com/emersion/go-message/pull/109

fix: import cycle not allowed

---

utf7/decoder.go
utf7/decoder_test.go

#389 utf7: reset ascii boolean at EOF while destination is short

---

client/client.go

client: Drop syscall.ECONNRESET hack from Client.readOnce

---

commands/fetch.go

When using one of the macros as fetch item arguments, the IMAP command
written to the socket would wrap the macro in parentheses, which is not
valid.
To address this we check whether there is only one item in the fetch
list and if it matches on of the macros we make sure it's serialized in
way that does not wrap it in parentheses.

Fix FETCH command with ALL, FAST and FULL macro as fetch items
