emersion/go-imap

client/client.go
client/cmd_any.go
client/cmd_any_test.go

In these changes I add two client Dialer functions that let us pass in a net.Dialer. Primarily I wanted to make it possible to add timeouts.
This is similar to the crypto/tls package's DialWithDialer function: https://godoc.org/crypto/tls#DialWithDialer
It is likely possible to do something similar using the already present client.New function, but I figure this is a little bit of a nicer interface.
I also expose a way to retrieve the underlying imap.Conn/net.Conn to the client. Again this is because I want to be able to add timeouts (or rather, set a deadline).
Why? Well, I have a small program that runs from cron to check an IMAP mailbox. I found that sometimes the program hangs seemingly forever. Today I have 9 stuck running for example.
If I strace one of them I see this:
```
strace: …
```

Add client Dial functions with net.Dialer parameters

---

README.md

Don't need the done channel because messages channel is being closed by the call to client.Fetch.

Simplify showcased client code

---

client/client.go
client/client_test.go
client/cmd_any.go
client/cmd_noauth.go
client/cmd_noauth_test.go

Hi again!
This is to resolve a panic I encountered:
```
panic: assignment to entry in nil map
goroutine 37 [running]:
panic(0x8253380, 0x18768800)
/home/will/bin/go-src/src/runtime/panic.go:500 +0x331
github.com/emersion/go-imap/client.(*Client).gotStatusCaps(0x189f8fa0, 0x18788798, 0x14, 0x15)
/home/will/code/go/src/github.com/emersion/go-imap/client/client.go:234 +0x12c
github.com/emersion/go-imap/client.(*Client).handleUnilateral(0x189f8fa0)
/home/will/code/go/src/github.com/emersion/go-imap/client/client.go:314 +0xbc5
created by github.com/emersion/go-imap/client.New
/home/will/code/go/src/github.com/emersion/go-imap/client/client.go:435 +0x3c2
```
From what I can gather, there are at least two goroutines that will access this map. `handleUnilateral()`, and when using functions such …

Use a mutex to protect access the client Caps map

---

client/cmd_auth.go

[RFC3501](https://tools.ietf.org/html/rfc3501) is the one that discusses IMAP4rev1

Correct RFC number for STATUS command

---

client/client.go
client/client_test.go

@jim-minter, what do you think?
Fixes #136

Replace various update channels with one unique channel

---

client/cmd_noauth.go
client/cmd_noauth_test.go

The current condition:
```
c.State() != imap.NotAuthenticatedState
```
give an confused message already login since when client state is `imap.LogoutState`. The client is already login only if it's in `imap.AuthenticatedState` or `imap.SelectedState`.

Fix login state checking condition

---

client/client.go

According to issue [#140](https://github.com/emersion/go-imap/issues/140)

Client - FIXED: return err to chan, from c.read()

---

message.go
message_test.go

An email from outlook.com contained an embedded part with
Content-ID and filename starting with a long sequence of
digits:
279351849188E3D84D6DCC5B@namprd05.prod.outlook.com
When sent unquoted, the Apple Mail IMAP client attempts to
parse this initially as an integer. When it overflows a
uint32 parsing is stopped, so the message contents are never
displayed.
Quoting all parameter values is safe and avoids this.
Indeed the IMAP RFC includes examples of far more aggressive
quoting of almost all strings from a MIME message.
That may be worth considering in the future

imap: quote parameter values

---

mailbox.go
message.go
server/server.go

Hi, we updated some exported function comments based on best practices from [Effective Go](https://golang.org/doc/effective_go.html#commentary). It’s admittedly a relatively minor fix up. Does this help you?

Fix function comments based on best practices from Effective Go

---

read.go
read_test.go

Handled by most wide-spread server implementations. Makes debugging easier because you can use utilities like netcat to directly talk to server.

Accept LF as command separator

---

backend/backend.go
backend/memory/backend.go
conn.go
server/cmd_noauth.go
server/conn.go
server/server.go

Similar to go-smtp's ConnectionState. For https://github.com/emersion/maddy/issues/29. Breaking change.
Closes #232.

Pass basic connection information to backend

---

commands/store.go
server/cmd_selected_test.go

See https://github.com/emersion/go-imap/issues/243#issuecomment-492411070.
ABNF:
```
store-att-flags = (["+" / "-"] "FLAGS" [".SILENT"]) SP
(flag-list / (flag *(SP flag)))
```

Handle "STORE FLAGS seqset flag1 flag2" syntax

---

server/cmd_any_test.go
server/cmd_auth_test.go
server/cmd_noauth_test.go
server/cmd_selected_test.go
server/server_test.go

It removes flood of "use of closed connection" errors from stderr.

Change order of defer statements in tests

---

client/client.go
client/cmd_noauth.go

This allows library users to call Client.StartTLS and DialWithDialerTLS with
a nil tls.Config.

client: prepopulate tls.Config.ServerName

---

message.go

Text attachment disposition params are now correctly parsed. Fixes #237

Make MIMEType and MIMESubType string comparisons case insensitive (#237)

---

backend/backendutil/search.go
backend/backendutil/search_test.go
backend/memory/message.go

From https://tools.ietf.org/html/rfc3501#page-50:
>The OPTIONAL [CHARSET] specification consists of the word
>"CHARSET" followed by a registered [CHARSET].  It indicates the
>[CHARSET] of the strings that appear in the search criteria.
>[MIME-IMB] content transfer encodings, **and [MIME-HDRS] strings in
>[RFC-2822]/[MIME-IMB] headers, MUST be decoded before comparing
>text in a [CHARSET] other than US-ASCII.**  US-ASCII MUST be
>supported; other [CHARSET]s MAY be supported.

Revert "backendutil: Use textproto directly for Match"

---

backend/backendutil/search.go
backend/backendutil/search_test.go
go.mod

After checking [RFC 2047](https://tools.ietf.org/html/rfc2047) I came to the conclusion that encoded values are allowed almost everywhere. Does it worth it checking whether a particular field is allowed to contain encoded values?
I also added a slightly extended test case I posted with the issue.
Closes #269.

backendutil: Decode headers in Match before comparsion

---

client/client.go
client/cmd_noauth_test.go
write.go
write_test.go

client: Use non-synchronizing literals when length is small (<4096)

---

backend/backendutil/body.go
backend/backendutil/body_test.go

This is partial implementation since BODY[something.1] should be also handled for nested messages, but FetchBodySection doesn't seem to support nested messages at all, so let's leave it for another time.

backendutil: Handle BODY[1] for non-multipart messages

---

server/cmd_noauth.go
server/cmd_noauth_test.go

Clients should be re-requesting it as per https://tools.ietf.org/html/rfc3501#section-6.2.1.
This fixes k9 mail for Android, which gets confused by receiving an unsolicited command straight after the TLS connection has been made.

Don't send CAPABILITY statement unsolicited after starting TLS connections. 

---

client/cmd_selected_test.go
commands/search.go

Right now, the SEARCH command sends something like this:
>  PMn5AW UID SEARCH CHARSET "UTF-8" 1:*
However, those quotes surrounding "UTF-8" seem to be troublesome, at least when talking to the GreenMail server (http://www.icegreen.com/greenmail).
Reading the RFC (https://tools.ietf.org/html/rfc3501#page-49) does not help to understand if those quotes are required or not **but** searching on google for "UID SEARCH CHARSET" seems to return results where quotes are not being used.
This Pull Request removes those quotes (and now GreenMail works as expected).
In any case, feel free to discard this PR if you consider this is something that should be fixed in GreenMail's source code instead of here.
Thanks!

Make SEARCH charset a RawString

---

commands/authenticate.go

>scanner.Scan returns false but scanner.Err returns nil in case of EOF.
See https://github.com/foxcpp/maddy/issues/143.

commands: Properly handle EOF in Authenticate.Handle

---

client/cmd_selected_test.go
client/example_test.go
search.go
search_test.go

See #324. Please note this does not fully validate the keywords. In particular, it does not check keywords against forbidden characters. Though possible, this would involve bigger changes, and more tests.

Fix the format of keyword flags

---

client/cmd_selected.go
search.go
search_test.go

Signed-off-by: Arnold Bechtoldt <arnold.bechtoldt@inovex.de>
```
criteria := imap.NewSearchCriteria()
c.UidSearch(criteria) // returns: []  Error in IMAP command UID SEARCH: Missing search parameters (0.001 + 0.000 secs).
```
Current behaviour:
```
Z12hwA EXAMINE INBOX
* FLAGS (\Answered \Flagged \Deleted \Seen \Draft)
* OK [PERMANENTFLAGS ()] Read-only mailbox.
* 6 EXISTS
* 6 RECENT
* OK [UNSEEN 1] First unseen.
* OK [UIDVALIDITY 1578248986] UIDs valid
* OK [UIDNEXT 7] Predicted next UID
Z12hwA OK [READ-ONLY] Examine completed (0.001 + 0.000 secs).
hw_TVQ UID SEARCH CHARSET UTF-8
hw_TVQ BAD Error in IMAP command UID SEARCH: Missing search parameters (0.001 + 0.000 secs).
IximMg LOGOUT
* BYE Logging out
IximMg OK Logout completed (0.001 + 0.000 secs).
```

Support ALL criteria in SEARCH

---

backend/updates.go
server/server.go

By RFC any untagged response can be send from server anytime. INFO is useful to notify client that new mailbox was created on server. This adds only support for this update but for v2 would be good to have ability to send update of any kind. Probably `Update` interface could contain function to generate response and even if go-imap do not support some update any app could create add without need to change `listenUpdates` in go-imap server.

Add MailboxInfoUpdate

---

backend/mailbox.go
backend/memory/mailbox.go
backend/memory/user.go
backend/user.go
server/cmd_auth.go

~~This change is backward compatible with v1.~~
go-imap-unselect needs an update to avoid 'leaking' mailboxes, I propose to merge it into go-imap along the way per #322.
Closes #337.

server: Add Mailbox.Close, make ListMailboxes return MailboxInfo

---

go.mod
mailbox.go
read.go
responses/list_test.go

This fixes #329.
In order to make this a non-breaking change I introduce a boolean to indicate whether the delimiter is NIL or not.
~~Also I hope it's okay to include testify. If not, I'll switch to using standard lib.~~ removed testify

Support NIL heirarchy delimiter

---

server/cmd_auth.go

Fixes #351 
(also includes a little tidyup that the linter spotted)

Error when selecting should unselect

---

server/server.go

After asking in the IRC about the comments above the Enable and EnableAuth methods, I was told that the comment was probably wrong.
This PR replaces them with links to the wiki pages

server: rewrite misleading comment about Enable and EnableAuth usage

---

message.go
message_test.go

Regarding #383
`TestBodyStructure_Format` does not pass right now because the BodyStructure contains lowercased values of the input string. So when it's formatted, its field list does not match the input.
I could:
1. Move the case out of `bodyStructureTests` into its own test function that does the equivalent of `TestBodyStructure_Parse` on that one case.
2. Add an optional member to the `bodyStructureTests` element struct type to allow overriding the expected value instead of `formatFields(test.fields)`.
The first option seems less freaky. I thought I'd ask in case you have better ideas or preferences.

imap: lower some fields + content disposition keys

---

message.go

Server can return nil for a body part, when it's empty but still there. RFC3501 says clients should treat this same as empty string. This patch implements that behavior.

return empty reader instead of nil when BODY is found but server returns nil

---

message.go
message_test.go

Currently when an email contains `To: undisclosed-recipients:;` in the header, `go-imap` parses this as one address with just a mailbox field, and one with all `nill` fields. Calling `.Address()` on them creates an array with `<undisclosed-recipients@>, <@>`.
The reason is that `go-imap` does not support empty groups, see e.g. :
```
Appendix A.1.3.  Group Addresses
----
From: Pete <pete@silly.example>
To: A Group:Ed Jones <c@a.test>,joe@where.test,John <jdoe@one.test>;
Cc: Undisclosed recipients:;
Date: Thu, 13 Feb 1969 23:32:54 -0330
Message-ID: <testabcd.1234@silly.example>
Testing.
----
In this message, the "To:" field has a single group recipient named
"A Group", which contains 3 addresses, and a "Cc:" field with an
empty group recipient named Undisclosed recipients.
``` 
in …

add support for empty groups in address lists

---

responses/fetch.go

Hi,
I found message chan is not closed correctly if the client is closed without sending "logout" command.
How to produce:
Connect to imap server and start to fetch some messages, then kill the imap client.
"Fetch.WriteTo" function reead "r.Messages" chan, if see an error, it returns. But the backend is still writing messages to the chan. So the goroutine is stuck.
http://localhost:6061/debug/pprof/goroutine?debug=1
```
1 @ 0x10387f0 0x1006f5d 0x1006d25 0x17584a5 0x166a519 0x166a703 0x166b0af 0x166e314 0x166d51d 0x166fa54 0x1067c61
#	0x17584a4	Rigel/go/cmd/imap_server/backend.(*Mailbox).ListMessages+0x1034		/Users//work/src/Rigel/go/cmd/imap_server/backend/mailbox.go:168
#	0x166a518	Rigel/go/pkg/utils/eimap/go-imap/server.(*Fetch).handle+0x158 …
```

Message chan not closed

---

README.md

Found this small typo while reviewing the examples. Many thanks for this package!

Fix small typo in example's doc comment

---

utf7/decoder.go
utf7/decoder_test.go

Hello,  
Thanks for this useful library.  
In Japanese environment, I found a bug in decoding UTF-7.
In `decoder.Transform`, there are two cases to return `transform.ErrShortDst`.  
The second case occurs after decode Base64. This is the point.  
When whole decoded string cannot be passed to `dst`, next call of `decoder.Transform` will begin with decoding Base64(repeat last decode and try to copy them to `dst` again).  
So, `decoder.ascii` should be set `true` before return `transform.ErrShortDst`. Otherwise, misdetection of Null shift makes error.

utf7: reset ascii boolean after decode while destination is short.

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/issue_template.md

Reject issues for questions about go-imap and IMAP in general. Our
issue tracker is filled with questions that aren't actionable.
cc @foxcpp

Add issue template

---

client/cmd_selected.go
client/cmd_selected_test.go
responses/fetch.go

The server can send unilateral updates as part of fetch results. Those should be ignored by Fetch and be handled by the `Updates` channel.
This fixes #430.

Fetch: Ignore unilateral updates from the server

---

server/conn.go
server/server_test.go

IDLE was changed into a built-in extension, but the default capabilities list was never updated to include it. The go-imap/client library (and probably any other sane IMAP client) resorts to polling if the IDLE cap isn't present. This PR simply adds IDLE to the list.

Add IDLE to capabilities list

---

client/client.go
client/cmd_selected.go
client/cmd_selected_test.go

Add a UseUSASCII bool flag to the search criteria to indicate that this
charset should be used for the search command. Default charset remains
utf-8.
According to RFC 3501, the search command must only support us-ascii;
support for other charset is optional.
Currently, us-ascii is the fallback charset when the search command with
utf-8 returns a badcharset error. However, this means that we always
execute two search calls to servers that don't support utf-8. More
importantly, it often leads to a server-side disconnect after multiple
badcharset errors. This can be avoid with the proposed flag.

search: allow users to select us-ascii charset

---

commands/enable.go

fixes that the `ENABLE` command adds quote mark to the capabilities

Enable remove quote mark
